// Quotes from the Log Lady (Margaret Lanterman), Twin Peaks.
// Verbatim excerpts from the Log Lady Introductions, written by David Lynch
// and performed by Catherine E. Coulson for the 1993 Bravo re-airing.
// Source: Twin Peaks Wiki transcript of all 30 introductions.
const LOG_LADY_QUOTES = [
  "There are many stories in Twin Peaks. Some of them are sad, some funny. Some of them are stories of madness, of violence. Some are ordinary. Yet they all have about them a sense of mystery – the mystery of life.",
  "I carry a log, yes. Is it funny to you? It is not to me.",
  "Behind all things are reasons. Reasons can even explain the absurd.",
  "Do we have the time to learn the reasons behind human beings' varied behavior? I think not. Some take the time. Are they called detectives?",
  "Sometimes ideas, like men, jump up and say, 'Hello!' They introduce themselves, these ideas, with words – are they words? These ideas speak so strangely.",
  "All that we see in this world is based on someone's ideas.",
  "Some ideas can arrive in the form of a dream. I can say it again: Some ideas arrive in the form of a dream.",
  "There is a sadness in this world, for we are ignorant of many things.",
  "What is this thing called a tear?",
  "Will the sadness that makes me cry my heart out, will it ever end? The answer, of course, is yes. One day, the sadness will end.",
  "Even the ones who laugh are sometimes caught without an answer.",
  "Look in the mirror. What do you see? Is it a dream, or a nightmare?",
  "I can see the smoke. I can smell the fire. The battle is drawing nigh.",
  "The fire I speak of is not a kind fire.",
  "Sometimes when we see the eyes – those horrible times when we see the eyes – eyes that have no soul, then we know a darkness.",
  "An evil man has a way, no matter how clever. To the trained eye, his way will show itself.",
  "Life, like music, has a rhythm. This particular song will end with three sharp sounds, like deathly drumbeats.",
  "There are things in life that exist, yet our eyes cannot see them.",
  "In a dream, are all the characters really you? Different aspects of you? Do answers come in dreams?",
  "As above, so below. The human being finds himself, or herself, in the middle.",
  "Where does creamed corn figure into the workings of the universe? What really is creamed corn? Is it a symbol for something else?",
  "Letters are symbols. They are building blocks of words, which form our language. Languages help us communicate.",
  "Sometimes nature plays tricks on us and we imagine we are something other than what we truly are.",
  "A wise person once said with a smile, the answer is within the question.",
  "As the night wind blows, the boughs move to and fro; the rustling, the magic rustling that brings on the dark dream.",
  "Woe to ones who behold the pale horse.",
  "Balance is the key. Balance is the key to many things.",
  "There is a depression after an answer is given. It was almost fun not knowing.",
  "Nothing is simple. We live in a world where nothing is simple.",
  "We paint our future with every present brush stroke.",
  "Nature is the great teacher. Who is the principal?",
  "My husband died in a fire. No one can know my sorrow. My love is gone. Yet, I feel him near me.",
  "When I see a fire, I feel my anger rising. This was not a friendly fire.",
  "Love, like blood, flows from the heart. Are blood and love related? Is love the blood of the universe?",
  "We are judged as human beings on how we treat our fellow human beings.",
  "If you have hurt someone, don't wait another day before making things right. The world could break apart with sadness in the meantime.",
  "The beautiful thing about treasure is that it exists. It exists to be found.",
  "There are clues everywhere, all around us. But the puzzle maker is clever.",
  "Our world is a magical smoke screen.",
  "A log is a portion of a tree. At the end of a crosscut log there are rings. Each ring represents one year in the life of the tree.",
  "My log hears things I cannot hear. But my log tells me about the sounds, about the new words. Even though it has stopped growing larger, my log is aware.",
  "Where there was once one, there are now two. Or were there always two?",
  "Only when we are everywhere will there be just one.",
  "It has been a pleasure speaking to you.",
];
